// generated by ./mk-headers.sh from main.c on 2022-02-26 at 11:46:40
#ifndef _main_h_
#define _main_h_
#define WID 800
#define HGT 600
#include <SDL.h>
extern SDL_Renderer *renderer;
#endif // _main_h_
