// generated by ./mk-headers.sh from parts.c on 2022-02-26 at 11:54:14
#ifndef _parts_h_
#define _parts_h_
#include <SDL.h>
void parts_init();
void parts_draw( SDL_Renderer *renderer );
void parts_update( float dt );
#endif // _parts_h_
